name: Go Password

on: 
    push:
        tags:
            - '*'

jobs:

    goreleaser: 
        name: Go releaser build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup Go
              uses: actions/setup-go@v2
            
            - name: Setup GoReleaser
              uses: goreleaser/goreleaser-action@v2
              with:
                  distribution: goreleaser
                  args: release --clean
              env:
                GITHUB_TOKEN: ${{ secrets.GO_GITHUB_TOKEN }}
                BREW_TOKEN: ${{ secrets.BREW_TOKEN }}
            
